analytics: {}
color:
  brandColors:
    - '#FDFFFE'
    - '#863903'
    - '#410101'
    - '#B08A5B'
    - '#DFC094'
  brandStrength: 0.653153
  lightness: 0.652027
  rhythmicContrast: 0.695945
  saturation: 0.691441
cta: {}
layout_spectrum: 1
name: Georg Streuber
opengraph: {}
purpose: []
typography_spectrum: 0.61437
