analytics: {}
color:
  brandColors:
    - '#FDFFFE'
    - '#863903'
    - '#410101'
    - '#B08A5B'
    - '#DFC094'
  brandStrength: 0.833333
  lightness: 0.332207
  rhythmicContrast: 0.871621
  saturation: 0.252252
cta: {}
layout_spectrum: 1
name: Georg Streuber
opengraph: {}
purpose: []
typography_spectrum: 0.61437
