analytics: {}
color:
  brandColors:
    - '#0B0803'
    - '#3D423C'
    - '#BDCAD0'
    - '#FFFFF2'
    - '#5B5D5C'
  brandStrength: 0.375
  lightness: 0.625
  rhythmicContrast: 0.75
  saturation: 0.1875
cta: {}
layout_spectrum: 0
name: Georg Streuber
opengraph: {}
purpose: []
typography_spectrum: 0.698479
