analytics: {}
color:
  brandColors:
    - '#C0A8A8'
    - '#201090'
    - '#887040'
    - '#10A8E8'
    - '#000000'
  brandStrength: 0.1875
  lightness: 0.25
  rhythmicContrast: 1
  saturation: 0.0625
cta: {}
layout_spectrum: 1
name: Georg Streuber
opengraph: {}
purpose: []
typography_spectrum: 0.61437
