name: Georg Streuber
favicon: null
layout_spectrum: 0.90323
typography_spectrum: 0.61437
title: artist website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FDFFFE'
    - '#863903'
    - '#410101'
    - '#B08A5B'
    - '#DFC094'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
