name: Georg Streuber
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61437
title: artist page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00418e'
    - '#30940e'
    - '#f2f0d9'
    - '#aca59e'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
