name: Georg Streuber
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61437
title: homepage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#313830'
    - '#9c9ba1'
    - '#0f1910'
    - '#6b7983'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
