name: Georg Streuber
favicon: null
layout_spectrum: 1
typography_spectrum: 0.698479
title: artist page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0B0803'
    - '#3D423C'
    - '#BDCAD0'
    - '#FFFFF2'
    - '#5B5D5C'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
